# Generated by Django 6.0.4 on 2026-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("logotipo", models.ImageField(upload_to="tecnologias/")),
                ("link_oficial", models.URLField()),
                ("nivel_interesse", models.IntegerField()),
            ],
        ),
    ]
