# Generated by Django 6.0.4 on 2026-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_projeto_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
    ]
