# Generated by Django 6.0.4 on 2026-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tfc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tfc",
            old_name="resumo",
            new_name="sumario",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="destaque",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="link",
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciaturas",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias_usadas",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
