# Generated by Django 6.0.4 on 2026-04-29 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_rename_resumo_tfc_sumario_remove_tfc_ano_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição do que a tecnologia faz e o que gostas/não gostas nela.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
